# build stage
FROM golang:1.17.7-alpine AS build-env
RUN apk update && apk upgrade && \
    apk --update add git make build-base
WORKDIR /src
COPY . .
RUN make build type=worker

# final stage
FROM alpine:latest
RUN apk update && apk upgrade && \
    apk --update --no-cache add tzdata
WORKDIR /app
COPY --from=build-env /src/portto-worker /app
COPY --from=build-env /src/config/*.yaml /app
ENTRYPOINT ./portto-worker