server:
  address: ":8080"

database:
  host: "127.0.0.1"
  # host: "mysql"
  port: 3306
  username: "demo"
  password: "demo123"
  dbname: "demo"

logger:
  level: "debug"

rpc:
  endpoint: "https://data-seed-prebsc-2-s3.binance.org:8545"
